REMOTE = https://intranet.dcs.qmul.ac.uk/repos/website/htdocs/dept/competition

changestr:
#	svn mv $(REMOTE)/2009/index.php $(REMOTE)/2008/index.php -m ""

#	svn checkout $(REMOTE)

#	svn mv $(REMOTE)/ARM-BW.jpg $(REMOTE)/2008/ARM-BW.jpg -m ""

#	svn mkdir $(REMOTE)/2009 -m ""

#	svn cp $(REMOTE)/2008/participants.php $(REMOTE)/2009/participants.php -m ""

#	svn add $(REMOTE)/Makefile
	svn commit -m ""
